### ISSUE TITLE
Fix display overlap with images

### ISSUE THREAD

**Issue by elaewin** [meklr/portfolio#3]
The graphic and your photo overlap in odd ways in the mobile version of the site.

**Comment by meklr** [comment]
I fiddled with it so it doesn't overlap, wanted feedback before I closed this issue. I just adjusted the size of the image file, and I'm not sure if it will look the same on other sites. I wish there was  a better way to set a responsive back-ground image. Tried a couple of thing with media query and couldn't figure anything out.
